# Generated by Django 5.1.1 on 2024-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(null=True, related_name='cart', to='shop.product'),
        ),
    ]
